### PR TITLE
Resolved 1 pipe limitation on WIN32 for Perl v5.20 and higher.

### PR DESCRIPTION
**Pull request by marioroy**
Hi @skaji,

I applied a fix so that this module allows multiple pipes/workers on WIN32 for Perl v5.20 and higher.

Regards,
Mario

### CODE REVIEW

**Comment by marioroy** [comment]
I used the following script to test.

```perl
use strict;
use warnings;

use Parallel::Pipes;
use Time::HiRes qw/sleep time/;

my $start = time;
my $numworkers = ($^O eq 'MSWin32' and $] lt '5.020000') ? 1 : 10;

my $pipes = Parallel::Pipes->new($numworkers, sub {
  my $num = shift;
  sleep 0.015; # simulate work
  $num;
});

my @back;

for my $i (1..500) {
  my @ready = $pipes->is_ready;
  for my $ready (grep $_->is_written, @ready) {
    push @back, $ready->read;
  }
  $ready[0]->write($i);
}

while (my @written = $pipes->is_written) {
  push @back, $_->read for @written;
}

$pipes->close;

printf "duration: %0.3f secs\n", time - $start;
printf "   items: %d\n", scalar @back;
```

Regards,

**Comment by skaji** [comment]
@marioroy Thanks 😄  I will have a look at it this weekend.

**Comment by marioroy** [comment]
@skaji The update works with Perl v5.20 and later releases. On Windows, the test script 01_basic.t (modified to run number_of_pipes5) using latest Test::Simple fails for Perl releases older than v5.20.

**Update:** It can fail with Perl v5.20. However, 01_basic.t (number_of_pipes5 enabled) is passing with Perl v5.24, v5.26, but not v5.22 and below.

**Comment by marioroy** [comment]
Another way is a pipe. This has lesser overhead than Thread::Queue and threads is not required.

Like with the Queue update, the test script 01_basic.t (number_of_pipes5 enabled) is passing with Perl v5.24, v5.26, but not v5.22 and below.

```diff
--- Pipes.pm.queue        2018-01-25 00:12:07.970204500 -0600
+++ Pipes.pm  2018-01-25 00:50:15.405937400 -0600
@@ -2,8 +2,6 @@
 use 5.008001;
 use strict;
 use warnings;
-use if $^O eq 'MSWin32', 'threads';
-use if $^O eq 'MSWin32', 'Thread::Queue';
 use IO::Handle;
 use IO::Select;

@@ -135,8 +133,8 @@

 sub new {
     my ($class, $number, $code) = @_;
-    if (WIN32 and $] lt '5.020000' and $number != 1) {
-        die "The number of pipes must be 1 under WIN32 Perl < v5.20 environment.\n";
+    if (WIN32 and $number != 1 and $] lt '5.024000') {
+        die "The number of pipes must be 1 under WIN32 for Perl older than v5.24.\n";
     }
     my $self = bless {
         code => $code,
@@ -146,7 +144,8 @@
     }, $class;

     if (WIN32) {
-        $self->{queue} = Thread::Queue->new();
+        pipe $self->{read_fh0}, $self->{write_fh0};
+        $self->{write_fh0}->autoflush(1);
     }
     if ($self->no_fork) {
         $self->{pipes}{-1} = Parallel::Pipe::Impl::NoFork->new(code => $self->{code});
@@ -172,7 +171,7 @@
         if (WIN32) {
             while (my $read = $there->read) {
                 my $data = $code->($read->{data});
-                $self->{queue}->enqueue($wid - 1);
+                syswrite $self->{write_fh0}, pack('S', $wid - 1), 2;
                 $there->write( $data );
             }
         } else {
@@ -204,8 +203,8 @@

     my @ready;
     if (WIN32) {
-        my $indx = $self->{queue}->dequeue();
-        push @ready, $pipes[$indx]->{read_fh};
+        sysread $self->{read_fh0}, my $indx, 2;
+        push @ready, $pipes[ unpack('S', $indx) ]->{read_fh};
     } else {
         my $select = IO::Select->new(map { $_->{read_fh} } @pipes);
         @ready = $select->can_read;
@@ -238,6 +237,10 @@
             warn "wait() unexpectedly returns $pid\n";
         }
     }
+    if (WIN32) {
+        close $self->{write_fh0};
+        close $self->{read_fh0};
+    }
 }

 1;
```

For stress testing, I edited 01_basic.t locally on my machine by commenting out sleep(0.01), replaced 30 with 3000 (3 places), and added entries for 10, 20, 30, 40, and 60 workers.

```perl
subtest number_of_pipes10 => sub { $subtest->(10) };
subtest number_of_pipes20 => sub { $subtest->(20) };
subtest number_of_pipes30 => sub { $subtest->(30) };
subtest number_of_pipes40 => sub { $subtest->(40) };
subtest number_of_pipes50 => sub { $subtest->(50) };
subtest number_of_pipes60 => sub { $subtest->(60) };
```

Testing completes successfully with Perl v5.24 and v5.26 only. I ran numerous times.

**Comment by marioroy** [comment]
Please feel free to disregard this pull request. This module is quite nice and wanted to understand the issues on the Windows platform. The patch works fine with Perl v5.12 and higher. However, Test::More subtest in 01_basic.t, called repeatedly, works only with Perl v5.24 and higher.

```perl
# Perl v5.24 and higher
subtest number_of_pipes10 => sub { $subtest->(10) };
subtest number_of_pipes20 => sub { $subtest->(20) };
subtest number_of_pipes30 => sub { $subtest->(30) };
```

```perl
# Perl v5.12 and higher
$subtest->(10);
$subtest->(20);
$subtest->(30);
```

**Comment by zmughal** [comment]
Hello all,

What kind of work would be needed to make this work completely in WIN32?

I'd like to see `cpm` work in parallel on WIN32 and this seems like a blocker for that.

**Pull request closed without merging**
